/**
 * Stub for Astro's virtual `astro:env/server` module.
 *
 * The real module is generated by the Astro build from the `env.schema` in
 * astro.config.mjs, so it does not exist when vitest loads a route module directly.
 * `vitest.config.ts` aliases the specifier here; individual tests override the values
 * with `vi.mock("astro:env/server", …)` when a specific secret matters.
 */
export const SUPABASE_URL: string | undefined = undefined;
export const SUPABASE_KEY: string | undefined = undefined;
export const OPENAI_API_KEY: string | undefined = undefined;
export const OPENAI_MODEL: string | undefined = undefined;
